### ISSUE TITLE
Error when compile with gcc 4.9

### ISSUE THREAD

**Issue by frisasky1** [jkivilin/metamod-p#13]
Compile with latest git i got following errors

> game_support.cpp: In function ‘const game_modinfo_t* lookup_game(const char*)’:
> game_support.cpp:90:63: error: a function-definition is not allowed here before ‘{’ token
>  mBOOL DLLINTERNAL install_gamedll(char *from, const char *to) {
>                                                                ^
> game_support.cpp:343:15: error: expected ‘}’ at end of input
>   return(mTRUE);
>                ^
> game_support.cpp:343:15: warning: control reaches end of non-void function [-Wreturn-type]
>   return(mTRUE);
>                ^
> Makefile:267: recipe for target 'opt.linux_i386/game_support.o' failed
> make: *** [opt.linux_i386/game_support.o] Error 1
>
